from app.core.db import Base


class BaseAbstractModel(Base):
    __abstract__ = True

    full_amount = ...
    invested_amount = ...
    fully_invested = ...
    create_date = ...
    close_date = ...
